version: '3.2'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    links:
      - db
  db:
    build: ./db
    ports:
      - "27017:27017"
  #db-seed:
  #  build: ./db-seed
  #  links:
  #    - db
  client:
    build: ./client
    ports:
      - "4200:4200"
