version: '3.2'
services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    links:
      - db
  db:
    build: ./db
    ports:
      - "27017:27017"

  #db-seed:
  #  build: ./db-seed
  #  links:
  #    - db
